filebeat.inputs:
  - type: filestream
    id: docker-json-logs
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container:
          stream: all
          format: docker

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - drop_event:
      when:
        not:
          regexp:
            message: '^\{'
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true
      when:
        regexp:
          message: '^\{'
  - drop_event:
      when:
        or:
          - equals:
              service.name: "filebeat"
          - regexp:
              container.name: ".*filebeat.*"
  - add_fields:
      target: platform
      fields:
        environment: local
        phase: phase-3

setup.template.name: "incident-ai-logs"
setup.template.pattern: "incident-ai-logs-*"
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "incident-ai-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"
