services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.3
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    depends_on:
      - elasticsearch
    volumes:
      - ./observability/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_app
      POSTGRES_PASSWORD: user_secret
    ports:
      - "5433:5432"
    volumes:
      - ./db/init/user-init.sql:/docker-entrypoint-initdb.d/init.sql

  order-db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_app
      POSTGRES_PASSWORD: order_secret
    ports:
      - "5434:5432"
    volumes:
      - ./db/init/order-init.sql:/docker-entrypoint-initdb.d/init.sql

  payment-db:
    image: postgres:16
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_app
      POSTGRES_PASSWORD: payment_secret
    ports:
      - "5435:5432"
    volumes:
      - ./db/init/payment-init.sql:/docker-entrypoint-initdb.d/init.sql

  notification-db:
    image: postgres:16
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_app
      POSTGRES_PASSWORD: notification_secret
    ports:
      - "5436:5432"
    volumes:
      - ./db/init/notification-init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build: ./user-service
    environment:
      SERVER_PORT: 8081
      DB_HOST: user-db
      DB_PORT: 5432
      DB_NAME: user_db
      DB_USER: user_app
      DB_PASSWORD: user_secret
    depends_on:
      - user-db
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    environment:
      SERVER_PORT: 8082
      DB_HOST: order-db
      DB_PORT: 5432
      DB_NAME: order_db
      DB_USER: order_app
      DB_PASSWORD: order_secret
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - order-db
      - kafka
    ports:
      - "8082:8082"

  payment-service:
    build: ./payment-service
    environment:
      SERVER_PORT: 8083
      DB_HOST: payment-db
      DB_PORT: 5432
      DB_NAME: payment_db
      DB_USER: payment_app
      DB_PASSWORD: payment_secret
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: payment-service-group
    depends_on:
      - payment-db
      - kafka
    ports:
      - "8083:8083"

  notification-service:
    build: ./notification-service
    environment:
      SERVER_PORT: 8084
      DB_HOST: notification-db
      DB_PORT: 5432
      DB_NAME: notification_db
      DB_USER: notification_app
      DB_PASSWORD: notification_secret
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: notification-service-group
    depends_on:
      - notification-db
      - kafka
    ports:
      - "8084:8084"

  api-gateway:
    build: ./api-gateway
    environment:
      SERVER_PORT: 8080
      USER_SERVICE_URL: http://user-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
      PAYMENT_SERVICE_URL: http://payment-service:8083
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
    depends_on:
      - user-service
      - order-service
      - payment-service
      - notification-service
    ports:
      - "8080:8080"

volumes:
  es-data:
